### ISSUE TITLE
Angular Excel Exporter does not work on Ipad device

### ISSUE THREAD

**Issue by hernancantori** [IgniteUI/igniteui-angular-samples#2649] opened 2021-04-28 20:20 UTC
### Description  
Calling the export method from **excelExportService** does not generate Excel file, browsing Angular App on an Ipad device.
Same thing happens on the samples given in Grid component.

### Steps to reproduce  

1. Browse https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/export-excel **on Ipad device** and click on the button "Export Grid to Excel" from the samples.

### Result  
After clicking on the button, nothing happens.

### Expected result  
To generate Excel file with grid data.

**Comment by zhosti** [comment] 2021-05-14 13:39
Hello @hernancantori, we investigated this issue and found that it is a bug in iOS versions prior to 13. We will implement a workaround that is expected to resolve the problem for older iOS versions. Essentially, it would open up the exported file in the browser so the user can download it if needed. 
Meanwhile, could you, please, tell us the iOS version you use?

**Comment by zhosti** [comment] 2021-05-21 08:08
Hello @hernancantori, after we started the implementation for the workaround that supposed to resolve the problem, we found that it does not completely solve it, because the fix does not apply to all browsers.
This issue is based on the general iOS WebKit download attribute issue. The download attribute in iOS is not working, therefore the browser does not recognize the generated ObjectUrl as download. This issue cannot be resolved by WebKit itself, because it involves iOS proprietary code, which is the reason why all browsers on iOS are affected.
This is a problem to iOS versions prior to 13. So we suggest an update of the iOS version to 13 or above, if it’s possible.

**Comment by hernancantori** [comment] 2021-05-21 11:52
Hi zhosti! My Ipad device has iOS version 14.3 (6th generation), but still the export to Excel doesn´t work.

Please advice.

![image](https://user-images.githubusercontent.com/9123120/119133020-cb1fc780-ba11-11eb-9649-e048053cccc5.png)

**Comment by zhosti** [comment] 2021-05-21 15:19
Hello @hernancantori, thank you for your information! We have tested the Excel export on a Safari browser on iOS version 14.4 and there is no problem with generating file, after your last comment we proceeded with further investigation. We’ve missed to make tests in the other browsers, so after we tested it in Chrome and Mozilla we successfully reproduced the problem. We can offer the following solution, excel file can be open in a browser tab and from there the user can decide what to do with it, but it will be different user experience from Safari.

**Closed** 2021-05-27 07:03 UTC
Labels: excel-exporter, status: resolved
