### ISSUE TITLE
IgxGrid sample (Boston Marathon) is cut out at paging area.

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular-samples#824] opened 2018-12-13 11:37 UTC
### Description  
IgxGrid sample (Boston Marathon) is cut out at paging area.

### Steps to reproduce  

1.Go to: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. Observe the first grid. 

### Result  
The grid is cut out at paging area.

### Expected result  
The grid should not be cut out at paging area.

### Attachments  
![image](https://user-images.githubusercontent.com/11095014/49936165-e8184e00-fedb-11e8-882a-f964e69b8076.png)

**Comment by mpavlinov** [comment] 2018-12-13 11:48
Duplicate of #815

**Closed by mpavlinov** 2018-12-13 11:48 UTC
Labels: bug, grid, severity: low, status: in-review
