### ISSUE TITLE
All Samples that have scrolling are having a space between the Horizontal and Vertical scroll

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular-samples#318] opened 2018-05-09 07:46 UTC
### Description  
Column resizing Demo vertical Scroll is not going all the way down when you resize a column to the right and the horizontal scroll appears. The rest are also having issues.

### Steps to reproduce  

1. Open Column resizing demo and you will see the the scroll is not stretch down to the end of the demo window. 

### Expected result  
The scroll var should be stretched all the way down. 

### Attachments  
![capture](https://user-images.githubusercontent.com/33216749/39802190-1548dfbe-5376-11e8-96a7-55c6b74dfade.PNG)

**Comment by MayaKirova** [comment] 2018-05-09 08:03
@SlavUI I cannot reproduce it neither on live nor on staging. Is perhaps the page zoomed out on your browser?
If so this is a duplicate of the following issue:
https://github.com/IgniteUI/igniteui-angular/issues/1207

**Closed** 2018-05-09 12:05 UTC
Labels: bug, severity: high, status: cannot-reproduce
