### ISSUE TITLE
Calendar header is missing when Bootstrap Light or Bootstrap Dark theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1793] opened 2020-02-17 15:47 UTC
### Description  
Calendar header is missing when Bootstrap Light or Bootstrap Dark theme is applied

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/calendar.html
2. Apply a Bootstrap Light or Bootstrap Dark theme
3. Look at the calendar header

### Result  
Calendar header is missing

### Expected result  
Calendar header should not be missing

### Attachments  
![calendar](https://user-images.githubusercontent.com/15327632/74668259-858ca300-51ad-11ea-82fd-85cec02c173e.jpg)

**Comment by simeonoff** [comment] 2020-02-24 15:29
Closing this as the header missing in the bootstrap theme is by design.

**Closed by simeonoff** 2020-02-24 15:29 UTC
Labels: calendar, status: in-review
