### ISSUE TITLE
Paginator select options are not visible when a dark theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1698] opened 2020-01-28 09:46 UTC
**Description**  

Paginator select options in Data Grid and Tree Grid are not visible when Material Dark or Fluent Dark theme is applied.

**Steps to reproduce**  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html or https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html
2. Apply a dark theme
3. Click on the paginator select to choose how many items per page you want to be displayed 

### Result  
Paginator select options are not visible

### Expected result  
Paginator select options should be visible when a dark theme is applied

### Attachments  
![paginator](https://user-images.githubusercontent.com/15327632/73252111-e1719680-41c2-11ea-91d7-faa50d83318e.jpg)

**Comment by simeonoff** [comment] 2020-02-24 15:19
Closing as the issue is fixed in the latest version of Ignite UI for Angular

**Closed by simeonoff** 2020-02-24 15:19 UTC
Labels: paging, status: in-review
