### ISSUE TITLE
Grid/TreeGrid Re-templating filter cell sample doesn't show any data

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-angular-samples#2642] opened 2021-04-27 08:27 UTC
### Description  
Re-templating filter cell sample doesn't show any data

### Steps to reproduce  
Grid

1. Open [https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering#re-templating-filter-cell](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering#re-templating-filter-cell)
or
[https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/grid/grid-filtering-template-sample](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/grid/grid-filtering-template-sample)

TreeGrid

1. Open [https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/filtering#re-templating-filter-cell](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/filtering#re-templating-filter-cell)
or
[https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/tree-grid/treegrid-filtering-template](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/vNext/angular-demos/tree-grid/treegrid-filtering-template)

### Result  
No records found
![image](https://user-images.githubusercontent.com/49060557/116209551-b6218280-a74a-11eb-8c4e-353d7aaf89be.png)

### Expected result  
Grid should be showing data

**Comment by gedinakova** [comment] 2021-04-27 08:30
Duplicate of #2621

**Closed** 2021-04-27 08:31 UTC
Labels: duplicate, grid, tree-grid
