### ISSUE TITLE
Toggle Demo content is not visible when a Dark theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1801] opened 2020-02-19 13:31 UTC
### Description  
Toggle Demo content is not visible when a Dark theme is applied

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/toggle.html
2. Click the toggle button in the demo
3. Apply a Dark theme

### Result  
The text in the box is not visible

### Expected result  
The text in the box should be visible

### Attachments  
![toggle](https://user-images.githubusercontent.com/15327632/74838794-df67a700-532c-11ea-9a85-d14fc9d97e5e.jpg)

**Comment by simeonoff** [comment] 2020-02-21 08:42
This is a duplicate of #1733.

**Closed by simeonoff** 2020-02-21 08:42 UTC
Labels: status: in-review, toggle
