### ISSUE TITLE
Error in the Tooltip sample

### ISSUE THREAD

**Issue by mtsvyatkova** [IgniteUI/igniteui-angular-samples#686] opened 2018-10-23 13:46 UTC
### Description  
Error is thrown when the Tooltip sample is opened in StackBlitz

### Steps to reproduce  

1. Open the Tooltip sample.
2. Click on the "View on Stackblitz" button.
3. Observe the result in StackBlitz.

### Result  
An error is thrown:

Error in igniteui-angular/lib/core/styles/base/utilities/_mixins.scss (228:12)
argument `$map` of `map-get($map, $key)` must be a map

Backtrace:
sass/igniteui-angular/lib/core/styles/base/utilities/_mixins.scss:228, in function `map-get`
sass/igniteui-angular/lib/core/styles/base/utilities/_mixins.scss:228, in mixin `igx-root-css-vars`
sass/igniteui-angular/lib/core/styles/components/ripple/_ripple-theme.scss:38, in mixin `igx-ripple`
sass/igniteui-angular/lib/core/styles/themes/_index.scss:110, in mixin `igx-theme`
sass/~/styles.scss:4

### Expected result  
The sample is loaded in StackBlitz.

### Attachments  
![error](https://user-images.githubusercontent.com/11231206/47364819-dcca5280-d6e2-11e8-8d9c-ac5f8bb1aa62.PNG)

**Comment by tachojelev** [comment] 2018-10-24 09:20
This seems to be a common error that is reproduced on all the samples.
For more details, refer to this [issue](https://github.com/IgniteUI/igniteui-angular/issues/2814). Once it gets fixed, the tooltip sample should be fixed as well.

**Closed** 2018-11-07 12:31 UTC
Labels: bug, severity: high, status: resolved, tooltip
