### ISSUE TITLE
some controls do not show in Edge

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular-samples#64] opened 2018-02-14 16:03 UTC
### Description  
A number of the controls get 'stuck' in a loading state upon visiting the documentation:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/circular_progress.html
https://www.infragistics.com/products/ignite-ui-angular/angular/components/dialog.html
https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider.html

May be more, didn't test exhaustively.

### Steps to reproduce  

1. Go to URL
2. ...
3. profit

### Result  
Control starts to load, then the loading circle freezes.

### Expected result  
Control loads and displays.

### Attachments  
![ngedge0](https://user-images.githubusercontent.com/16783024/36214142-ad7c0514-1176-11e8-8da5-60fc410a997c.PNG)
![ngedge](https://user-images.githubusercontent.com/16783024/36214143-ad8ac676-1176-11e8-9e3b-09d52eebcf63.PNG)

**Comment by kdinev** [comment] 2018-02-16 08:28
Duplicate of #43

**Closed by kdinev** 2018-02-16 08:28 UTC
