### ISSUE TITLE
A couple of grid row selection samples have disabled Stackblitz buttons.

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-samples#1755] opened 2020-02-10 11:55 UTC
### Description  
A couple of grid row selection sample have disabled Stackblitz buttons.

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html
2. Examine the Stackblitz buttons of the following samples:

- Row Numbering Demo

- Excel Style Row Selectors Demo

- Conditional Selection Demo

### Result  
The samples' Stackblitz buttons are disabled.

### Expected result  
The buttons should be enabled.

There are disabled buttons in the following topics as well:
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row_selection.html

https://staging.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/row_selection.html

**Comment by HristoP96** [comment] 2020-02-14 08:23
The issue is fixed with this PR - [https://github.com/IgniteUI/igniteui-docfx/pull/1772](https://github.com/IgniteUI/igniteui-docfx/pull/1772)

**Closed by HristoP96** 2020-02-14 08:23 UTC
Labels: bug, grid, severity: medium, status: in-review, version: 9.0.x
