### ISSUE TITLE
Pinning icons are not correctly changed when tapping on them on touch

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#510] opened 2018-07-05 13:59 UTC
### Description  
When you tap to pin column or to unpin column, the pinning icon gets the opposite style

### Steps to reproduce  

1. Run the grid-pinning sample on touch (Ipad for example)
2. Unpin Contact title column
3. Pin it again

### Result  
The pinning icon gets light grey color

### Expected result  
The pinning icon should be dark grey

**Comment by alexalex972** [comment] 2018-08-16 10:40
That's a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/1959

**Closed by alexalex972** 2018-08-16 10:40 UTC
Labels: bug, grid, pinning, severity: low, status: in-development
