### ISSUE TITLE
The third Drag&Drop sample is missing

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular-samples#1710] opened 2020-01-31 08:03 UTC
### Description  
The sample is missing.

### Steps to reproduce  

1. Open https://staging.infragistics.com/angularsite/components/drag_drop.html#demo-2
2. The sample is missing

### Result  
The sample is missing

### Expected result  
The samples should be present

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment] 2020-01-31 13:23
Duplicate of #1708

**Closed** 2020-01-31 13:46 UTC
Labels: duplicate, grid, row-drag, version: 9.0.x
