### ISSUE TITLE
Boston Marathon Grid theming issues

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#3113] opened 2022-10-07 08:04 UTC
### Description  
Material dark theme

![image](https://user-images.githubusercontent.com/52001020/194504225-5362f25c-086e-46cf-a66c-8a710fa8c960.png)

**Comment by dkamburov** [comment] 2022-10-07 08:46
@radomirchev What's the issue here? Not seeing the word `FINISH`?
![image](https://user-images.githubusercontent.com/1182001/194512524-719e0987-d6a2-40fd-9b23-4c7a384127d5.png)

**Comment by hanastasov** [comment] 2022-10-07 12:34
duplicate of https://github.com/IgniteUI/igniteui-angular-samples/issues/3086

**Comment by radomirchev** [comment] 2022-10-19 10:24
@dkamburov switch to "Material dark theme" or any other dark theme. Visible from the screenshot, the "Finish" word is not readable and the pop up is not themed.

**Closed** 2022-10-19 14:41 UTC
Labels: :eyes: status: in-review
