### ISSUE TITLE
Tree grid's row reorder demo is not loaded in stackblitz.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular-samples#1334] opened 2019-07-22 15:22 UTC
### Description  
An import error is thrown.

### Steps to reproduce  

1. Navigate to Tree Grid > Row Drag topic
2. Scroll to the last demo
3. Open it in stackblitz.

### Result  
The following error is thrown:
Import error, can't find file:
../data/employees-flat

### Expected result  
The demo should be successfully loaded in Stackblitz.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by DiyanDimitrov** [comment] 2019-07-22 15:36
Duplicate of #1236

**Closed by DiyanDimitrov** 2019-07-22 15:36 UTC
Labels: category-StackBlitz, category-bug, ig-tree-grid, severity: medium, status: in-review
