### ISSUE TITLE
File not found resources-en.json

### ISSUE THREAD

**Issue by EmilTanev** [IgniteUI/igniteui-angular-samples#1230] opened 2019-06-28 08:10 UTC
Open any sample
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html

Error in the console
 https://staging.infragistics.com/resources-en.json?t=1559818870008 404 (Not Found)

**Comment by zdrawku** [comment] 2020-06-23 08:23
It looks like the initiator is `igniteui-theming-widget` :
https://cdn-na.infragistics.com/igniteui/theming-widget/latest/igniteui-theming-widget.js?t=?t=1592816316483

Unfortunately, this error is observed on production environment as well. Re-assigning this to @ChronosSF

**Comment by ChronosSF** [comment] 2020-06-23 08:34
@zdrawku , no this is because the theming widget is an angular component and uses zone.js which swallows and reemits errors. The bug is from 1 year ago and we didn't have the theming widget then

**Comment by simeonoff** [comment] 2020-07-27 07:52
@ChronosSF can we close this?

**Comment by ChronosSF** [comment] 2020-07-27 08:15
If it doesn't reproduce anymore, sure. 

Even if it reproduces, it doesn't affect the usability of the docfx site but we should still probably try not to have errors in the console.

**Comment by simeonoff** [comment] 2020-07-27 08:20
@zdrawku can you check and close?

**Comment by kdinev** [comment] 2021-02-19 12:57
@zdrawku Maybe check and close this one?

**Closed** 2021-03-31 10:43 UTC
Labels: status: in-review
