### ISSUE TITLE
Grid Remote Virtualization Demo r

### ISSUE THREAD

**Issue by alexalex972** [IgniteUI/igniteui-angular-samples#372] opened 2018-05-30 12:57 UTC
### Description  
Describe the issue.

### Steps to reproduce  

1. Step 1
2. Step 2
3. ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment] 2018-05-30 13:13
Duplicate of #374

**Closed by zdrawku** 2018-05-30 13:13 UTC
Labels: duplicate
