### ISSUE TITLE
Category Chart sample throws exceptions and doesn't show demo on samples website.

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular-samples#976] opened 2019-02-19 13:28 UTC
### Description  
Category Chart sample throws exceptions and doesn't show demo on samples website.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/categorychart.html
2. Observe the sample, open console where the errors are:
Uncaught TypeError: Cannot read property 'length' of undefined
and
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'charts/category-chart-overview-sample'
Error: Cannot match any routes. URL Segment: 'charts/category-chart-overview-sample'

### Result  
Sample doesn't appear on the page

### Expected result  
Sample should show demo presentation.

### Attachments  
![categorychart](https://user-images.githubusercontent.com/24592428/53018360-d6fb3880-345a-11e9-800c-bc49360b1154.PNG)
![consolechart](https://user-images.githubusercontent.com/24592428/53018364-d8c4fc00-345a-11e9-8dd2-69165d63024f.PNG)

**Comment by mpavlinov** [comment] 2019-02-19 14:50
@MartinKamenov It is working now. Please check it.

**Comment by MartinKamenov** [comment] 2019-02-19 15:01
@mpavlinov Yes, now it seems to be working.

**Comment by HUSSAR-mtrela** [comment] 2019-02-19 15:14
I confirmed and it works for me too. I'm closing this issue.

**Closed by HUSSAR-mtrela** 2019-02-19 15:14 UTC
Labels: bug, severity: high, status: in-review
