### ISSUE TITLE
Column pinning in grid-moving sample doesn't work on touch

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#509] opened 2018-07-05 13:50 UTC
### Description  
Tapping the pinning icons on touch changes only their styles, but the columns do not move

### Steps to reproduce  

1. Run the grid-moving sample on staging
2. Try to fix/unfix columns

### Result  
Columns cannot be fixed/unfixed

### Expected result  
Columns can be fixed/unfixed

**Comment by MayaKirova** [comment] 2018-07-06 11:28
This happens only on Safari IPad, cannot be reproduced in other touch devices.
The problem seems to be that when there is column moving enabled, elements inside the header don't trigger the click event handlers (possibly something prevents the event) on IPad. This does not seem to be  a problem with the sample.

**Comment by MayaKirova** [comment] 2018-07-06 11:37
Closing this since the issue is not in the sample.

**Closed by MayaKirova** 2018-07-06 11:37 UTC
Labels: bug, grid, pinning, severity: medium, status: in-development
