### ISSUE TITLE
Stackblitz buttons are disabled in all Column Moving topics.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular-samples#1227] opened 2019-06-28 06:42 UTC
### Description  
Stackblitz buttons are disabled in all Column Moving topics.

### Steps to reproduce  

1. Navigate to any Column Moving topic
2. Note the Stackblitz buttons on both samples

### Result  
The buttons are disabled.

### Expected result  
The buttons should be enabled.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by HristoP96** [comment] 2019-07-08 05:51
@gedinakova This is caused, because of the missing jsons for StackBlitz instantiation. The column moving styling sample is not yet in master, because of this PR - [https://github.com/IgniteUI/igniteui-angular-samples/pull/1213#issuecomment-506223714](https://github.com/IgniteUI/igniteui-angular-samples/pull/1213#issuecomment-506223714), once the PR is merged and a new build for staging is kicked, the issue won't reproduce anymore

**Comment by zdrawku** [comment] 2019-12-18 09:36
Fixed

**Closed by zdrawku** 2019-12-18 09:36 UTC
Labels: StackBlitz, bug, grid, status: in-review, version: 8.0.x
